name: dedop
dependencies:
#- IOOS::basemap=1.0.8.dev0=np110py35_1
#- IOOS::geos=3.4.2=vc14_1
#- IOOS::pyproj=1.9.5.1=py35_0
#- IOOS::pyshp=1.2.3=py35_0
- colorama=0.3.7=py35_0
- cycler=0.10.0=py35_0
- decorator=4.0.10=py35_0
- entrypoints=0.2.2=py35_0
- ipykernel=4.3.1=py35_0
- ipython=5.0.0=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.1=py35_0
- jinja2=2.8=py35_1
- jpeg=8d=vc14_0
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.3.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.1.0=py35_0
- libpng=1.6.22=vc14_0
- libtiff=4.0.6=vc14_2
- markupsafe=0.23=py35_2
- matplotlib=1.5.1=np110py35_0
- mistune=0.7.2=py35_0
- mkl=11.3.3=1
- nbconvert=4.2.0=py35_0
- nbformat=4.0.1=py35_0
- netcdf4=1.2.2=np110py35_0
- notebook=4.2.1=py35_0
- numpy=1.10.4=py35_2
- openssl=1.0.2h=vc14_0
- path.py=8.2.1=py35_0
- pickleshare=0.7.2=py35_0
- pip=8.1.2=py35_0
- prompt_toolkit=1.0.3=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=4.11.4=py35_6
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.4=py35_0
- pyzmq=15.2.0=py35_0
- qt=4.8.7=vc14_8
- qtconsole=4.2.1=py35_0
- scipy=0.17.1=np110py35_1
- setuptools=23.0.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.16.9=py35_2
- six=1.10.0=py35_0
- tk=8.5.18=vc14_0
- tornado=4.3=py35_1
- traitlets=4.2.1=py35_0
- vs2015_runtime=14.0.25123=0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- win_unicode_console=0.5=py35_0
- zlib=1.2.8=vc14_3
- pip:
  - basemap==1.0.8
  - ipython-genutils==0.1.0
  - jupyter-client==4.3.0
  - jupyter-console==5.0.0
  - jupyter-core==4.1.0
  - prompt-toolkit==1.0.3
  - pyproj==1.9.5.1
  - pyshp==1.2.3
  - win-unicode-console==0.5