name: dedop
channels:
    - conda-forge
    - ccitools
    - anaconda
dependencies:
    - python ==3.6
    - bokeh ==0.12.13
    - cate-util=1.0.0.dev1=py36_0
    - hdf4 ==4.2.12
    - ipywidgets ==7.1.1
    - jdcal ==1.3
    - jupyter ==1.0.0
    - netcdf4 ==1.2.4
    - matplotlib ==2.0.2
    - numexpr ==2.6.4
    - numpy ==1.11.3
    - pyproj ==1.9.5.1
    # pyqt >=5.6 clashes with matplotlib 1.5.1
    - pyqt ==5.6.0
    - qt ==5.6.2
    - scipy ==1.0.0
    - shapely ==1.6.2
    - xarray ==0.10.0
    #
    # for testing only
    #
    - pytest
    - pytest-cov