name: dedop
channels:
    - ccitools
dependencies:
    - python ==3.6
    - bokeh ==0.12.6
    - cate-util=0.9.0.dev4
    - hdf4 ==4.2.12
    - ipywidgets ==6.0.0
    - jupyter ==1.0.0
    - netcdf4 ==1.2.4
    - matplotlib >=2.0
    - numexpr ==2.6.2
    - numpy=1.11.3=py36_0
    - pyproj ==1.9.5.1
    # pyqt >=5.6 clashes with matplotlib 1.5.1
    - pyqt >=5.6
    - qt >=5.6
    - scipy=0.19.0=np111py36_0
    #
    # for testing only
    #
    - pytest
    - pytest-cov